### ISSUE TITLE
[HLSL] Frontend handling of "typed" resource types and buffer operations

### ISSUE THREAD

**Issue by damyanp** [llvm/llvm-project#101557]
- [x] #97362
- [x] #98556
- [x] llvm/llvm-project#98193
- [x] llvm/llvm-project#98556
- [x] llvm/llvm-project#102392
- [x] #102954
- [x] #104855
- [x] #107907
- [x] #104861
- [x] #95952
- [x] #95956
- [x] #84824
- [x] #105076
