### ISSUE TITLE
[llvm-lit] Enable lit internal shell by default

### ISSUE THREAD

**Issue by connieyzhu** [llvm/llvm-project#102704]
This is a meta-issue that addresses the problem referenced in [[RFC] Enabling the Lit Internal Shell by Default](https://discourse.llvm.org/t/rfc-enabling-the-lit-internal-shell-by-default/80179/18).

**Brief problem summary**: 
Many `RUN` line commands used in `LLVM` tests are written in a way that only works on POSIX-compliant shells, leading to issues on platforms like Windows or non-POSIX systems. To overcome these discrepancies, lit has an internal shell implementation designed to ensure uniform execution of these commands, regardless of the platform. Although the internal shell supports most common commands, it still lacks several capabilities that are necessary for it to become the default shell when running `LLVM` tests.

This meta-issue tracks the following issues:
**Subproject Issues**: 

- [ ] **[[llvm][llvm-lit] Enable internal shell for llvm test suite](https://github.com/llvm/llvm-project/issues/102697)**

> Missing Capabilities Blocking Enablement:
> - [ ] [cat -v](https://github.com/llvm/llvm-project/issues/102374) 
> - [ ] [env subcommand](https://github.com/llvm/llvm-project/issues/102383)
> - [ ] [Environment variable](https://github.com/llvm/llvm-project/issues/102395)

- [ ] **[[clang][llvm-lit] Enable internal shell for clang test suite](https://github.com/llvm/llvm-project/issues/102699)**

> Missing Capabilities Blocking Enablement:
> - [ ] [Environment variable](https://github.com/llvm/llvm-project/issues/102395) 
> - [ ] [Command substitution](https://github.com/llvm/llvm-project/issues/102384)
> - [ ] [Unhashable Type](https://github.com/llvm/llvm-project/issues/102389) 
> - [ ] [Expected string not found in input](https://github.com/llvm/llvm-project/issues/102695)

- [ ] **[[lld][llvm-lit] Enable internal shell for lld test suite](https://github.com/llvm/llvm-project/issues/102700)**

> Missing Capabilities Blocking Enablement:
> - [ ] [Environment variable](https://github.com/llvm/llvm-project/issues/102395) 
> - [ ] [Curly brace](https://github.com/llvm/llvm-project/issues/102382)

- [ ] **[[lldb][llvm-lit] Enable internal shell for lldb test suite](https://github.com/llvm/llvm-project/issues/102698)**

> Missing Capabilities Blocking Enablement:
> - [ ] [cat -e](https://github.com/llvm/llvm-project/issues/102377)
> - [ ] [No such file or directory](https://github.com/llvm/llvm-project/issues/102696)

- [ ] **[[BOLT][llvm-lit] Enable internal shell for BOLT test suite](https://github.com/llvm/llvm-project/issues/102701)**

> Missing Capabilities Blocking Enablement:
> - [ ] [|& syntax change](https://github.com/llvm/llvm-project/issues/102388)
> - [ ] [Parentheses](https://github.com/llvm/llvm-project/issues/102401)
> - [ ] [TypeError: String argument expected](https://github.com/llvm/llvm-project/issues/102693)
> - [ ] [Attributeerror](https://github.com/llvm/llvm-project/issues/102399) 

- [ ] **[[compiler-rt][llvm-lit] Enable internal shell for compiler-rt test suite](https://github.com/llvm/llvm-project/issues/102702)**

> Missing Capabilities Blocking Enablement:
> - [ ] [Environment variable](https://github.com/llvm/llvm-project/issues/102395) 
> - [ ] [Ulimit](https://github.com/llvm/llvm-project/issues/102398)
> - [ ] [Unset](https://github.com/llvm/llvm-project/issues/102397)
> - [ ] [Expected string not found in input](https://github.com/llvm/llvm-project/issues/102695)
> - [ ] [InternalShellError](https://github.com/llvm/llvm-project/issues/102386)
> - [ ] [Attribute Error](https://github.com/llvm/llvm-project/issues/102399)
> - [ ] [Unhashable Type](https://github.com/llvm/llvm-project/issues/102389)
> - [ ] [For loop](https://github.com/llvm/llvm-project/issues/102380)
> - [ ] [Unsupported redirect](https://github.com/llvm/llvm-project/issues/102385)
> - [ ] [Command substitution](https://github.com/llvm/llvm-project/issues/102384)
> - [ ] [Parentheses](https://github.com/llvm/llvm-project/issues/102401)
> - [ ] [No such file or directory](https://github.com/llvm/llvm-project/issues/102696)

This is a comprehensive list of all the features to be implemented.
**Feature List:**

- [ ] [cat -v](https://github.com/llvm/llvm-project/issues/102374) 
- [ ] [env subcommand](https://github.com/llvm/llvm-project/issues/102383)
- [ ] [Environment variable](https://github.com/llvm/llvm-project/issues/102395)
- [ ] [Command substitution](https://github.com/llvm/llvm-project/issues/102384)
- [ ] [Unhashable Type](https://github.com/llvm/llvm-project/issues/102389) 
- [ ] [Expected string not found in input](https://github.com/llvm/llvm-project/issues/102695)
- [ ] [Curly brace](https://github.com/llvm/llvm-project/issues/102382)
- [ ] [cat -e](https://github.com/llvm/llvm-project/issues/102377)
- [ ] [No such file or directory](https://github.com/llvm/llvm-project/issues/102696)
- [ ] [Ulimit](https://github.com/llvm/llvm-project/issues/102398)
- [ ] [Unset](https://github.com/llvm/llvm-project/issues/102397)
- [ ] [|& syntax change](https://github.com/llvm/llvm-project/issues/102388)
- [ ] [Parentheses](https://github.com/llvm/llvm-project/issues/102401)
- [ ] [TypeError: String argument expected](https://github.com/llvm/llvm-project/issues/102693)
- [ ] [Attribute Error](https://github.com/llvm/llvm-project/issues/102399)
- [ ] [InternalShellError](https://github.com/llvm/llvm-project/issues/102386)
- [ ] [For loop](https://github.com/llvm/llvm-project/issues/102380)
- [ ] [Unsupported redirect](https://github.com/llvm/llvm-project/issues/102385)

This issue will help track the progress of enabling the lit internal shell across all LLVM subprojects.

**Comment by connieyzhu** [comment]
@ldionne Hi there, it seems like libcxx in LLVM uses lit's internal shell as the default shell for running lit tests. Can you confirm if this is accurate?

**Comment by ldionne** [comment]
> @ldionne Hi there, it seems like libcxx in LLVM uses lit's internal shell as the default shell for running lit tests. Can you confirm if this is accurate?

Yes, that's right. We made the transition some time ago (maybe 1-3 years) and haven't looked back.
