### ISSUE TITLE
Meta issue to track changes for adding plugin and LLVM_BUILD_LLVM_DYLIB support for Windows

### ISSUE THREAD

**Issue by fsfod** [llvm/llvm-project#109483]
Some rational for these changes is explained in this old LLVM discourse post [Supporting LLVM_BUILD_LLVM_DYLIB on Windows](https://discourse.llvm.org/t/supporting-llvm-build-llvm-dylib-on-windows/58891).

## LLVM
- [x] #96630
- [x] #107873
- [ ] #108051
- [ ] #109024
- [x] #109156
- [ ] Switch to new visibility macros for X86 Target initialize functions definitions.
- [ ] Add visibility macros for Target initialize function declarations.
- [ ] Clang tooling generated visibility macros for LLVM.
- [ ] clang-cl template dllexport workaround.
- [ ] Default symbol visibility on non windows platforms set to hidden.
- [ ] MSVC deleted and defaulted class members changes.
- [ ] MSVC dllexport ilist fix or default template argument workaround.
- [ ] MSVC dllexport cl::opt fix or workaround.

## Clang
- [ ] #108276
- [ ] #109362 
- [ ] #109321
- [x] #109319
- [ ] Clang tooling generated visibility macros for Clang
- [ ] MSVC deleted and defaulted class members changes.

**Comment by annamthomas** [comment]
hi @fsfod , I'm having trouble building my local downstream fork of LLVM which uses dynamic build and link (i.e. these options are present: -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON). 

If I revert back to before the first change landed in this series, it builds completely fine. 
The reason is that we have some dynamic dependencies between our downstream library and LLVM and when building those files, it complains of same issue as reported here: https://github.com/llvm/llvm-project/issues/107687

i.e. 
```
[02:35:10] #include "llvm/CodeGen/GenVT.inc"
[02:35:10]          ^~~~~~~~~~~~~~~~~~~~~~~~
[02:35:10] 1 error generated.
```

Is there any workarounds you can suggest for this? I've tried adding the `-DLLVM_BUILD_LLVM_DYLIB_VIS=ON` but it does not help.

**Comment by fsfod** [comment]
I'm not sure why my changes would cause that file not to be generated. I did notice there was a merged PR thats looks similar to your issue https://github.com/llvm/llvm-project/pull/109306

**Comment by annamthomas** [comment]
I'm on truck but that didn't fix it.

After multiple iterations, what I see finally helped is reverting the change:
283c2c88: "[TableGen] Add explicit symbol visibility macros to code generated (#107873)"

And I can build on trunk. How does the visibility macros work actually?

**Comment by fsfod** [comment]
For non windows and i think mingw it would be turned in to `__attribute__((visibility("default")))` which is redundant atm because the default symbols visibility has not yet been changed to hidden. On windows platforms it should be empty unless LLVM_BUILD_LLVM_DYLIB_VIS is used.

**Comment by andrurogerz** [comment]
## Status
As of today, we're at just over 80% completion on annotating the LLVM public interface in llvm-project/main.

## Remaining work-items
- [ ] Merge outstanding changes from my [LLVM fork](https://github.com/llvm/llvm-project/compare/main...andrurogerz:llvm-project:llvm-abi). The fork currently builds LLVM as a DLL on Windows using MSVC and as a shared object file with default hidden visibility on Linux using clang.
- [ ] Re-define `LLVM_ABI` to always be `__attribute__(visibility(("default")))` on non-Windows rather than `[[gnu::visibility("default")]]`. 
  - Required to make attribute placement more flexible when using gcc, and allows us to remove the `LLVM_ABI_FRIEND`.
- [ ] Replace all instance of `LLVM_ABI_FRIEND` with `LLVM_ABI` and remove the definition of `LLVM_ABI_FRIEND`.
- [ ] Re-order all instances of `LLVM_ABI extern` variable declarations to be `extern LLVM_ABI`.
- [ ] Re-work and use the `LLVM_C_ABI` macro to annotate the `llvm-c` library. This library must not depend on llvm/Support/Compiler.h.
- [ ] Define a new macro for the `demangle` library. This library must not depend on llvm/Support/Compiler.h.
- [ ] Fix issues building DLL on Windows using clang-cl.

**Comment by vgvassilev** [comment]
Do we have a plan for clang? There we can probably land an all-in-one PR. Also we should probably land the ci to avoid regressing.

CC: @mcbarton

**Comment by compnerd** [comment]
@vgvassilev I think that clang will need to go through a similar process. I suggest that we do the following:

1. finish the annotations for LLVM
2. setup a build that enables the DLL mode builds for LLVM and builds tools with dynamic LLVM (binutils, clang, lldb, etc)
3. Follow this same process for converting clang to a DLL.

**Comment by andrurogerz** [comment]
We are now at 91% of annotations for the DLL build merged into llvm main.

**Comment by compnerd** [comment]
@aeubanks I don't mind moving the code over as a tool that we ship as part of llvm into clang/tools. Is that what you had in mind?

**Comment by compnerd** [comment]
> f you take a glance at https://github.com/llvm/llvm-project/pull/178006/changes, it's very obvious that a lot of things that definitely should be exported currently aren't. Heck, we don't even export the full C API right now, which is the bare minimum!

I completely agree, the full LLVM C API surface should be exposed (via `LLVM_C_ABI`).

> I don't understand what this has to do with binary size. Are you talking about optimizing parts of the dylib away with LTO? I wouldn't expect minor reductions in export surface to give any significant gains: Pretty much all parts of LLVM are needed by _something_, otherwise they wouldn't be there.

I haven't looked at the final results in a bit, but my concern with this is that the way C++ works forces us to do some things that are not ideal. Primarily, if we have APIs which are needed *internally* (across "components") and are part of classes, they end up being `public` in `llvm/include`. Those are *not* necessarily ABI - they are for internal use only. Those shouldn't be exported and you should be able to do "questionable" things (e.g. change CC) on those interfaces.

> As I have said before, I'm not at all opposed to reducing LLVM's ABI surface (and yes, we can do that, the ABI is explicitly not stable), but it needs to be done correctly:
> 
> * ABI exclusion should be explicitly considered by someone, not happen accidentally, by omission.
> * ABI exclusions needs to be explicitly marked, so that ids can distinguish the cases of "intentionally excluded from the ABI" and "forgotten to add an ABI annotation". IIRC we wanted to add an LLVM_NOT_ABI macro for this in past discussions. Otherwise it is impossible for us to have an ids workflow in CI.

I also completely agree with this. ABI exclusions absolutely need human intervention. The exclusions don't necessarily have to be marked, but marking them with something like `LLVM_SPI` or something similar is absolutely an option.

> Given the numbers [@Steelskin](https://github.com/Steelskin) mentioned, we're still very far away from the 64k limit, so I'm not sure why we're arguing about this.

I think that the concern is the rate of increase. But, it seems that the current delta is ~O(1000) which is really not worth the time and effort - we should just export these for now and figure out a path to reducing the ABI surface.

**Comment by Steelskin** [comment]
Circling back to this. I have spent the last few days working toward a more permanent solution to this problem, especially now that we have a few other interested customers. I have been trying various changes to idt, the workflow and the python script. This time around, I went in with the idea of applying the script to every single header and making sure we ended up with no spurious diff against the already-annotated tree.

Here is my plan right now:
1. Land some version of compnerd/ids#58. This contains all of the changes we need from the idt tool to make it work much better with the way the LLVM build works.
2. Update the workflow and the python script to use the new argument. This is done in this [WIP branch](https://github.com/llvm/llvm-project/compare/main...Steelskin:llvm-project:fabrice/temp-add-py-changes) which needs some further cleanups.
3. Land all of the missing LLVM_ABI annotations in a few changes. If you are curious, [this](https://github.com/llvm/llvm-project/compare/main...Steelskin:llvm-project:fabrice/fix-llvm-abi-annotations) is what I ended up with. This touches about ~600 files so I want to break it down to something manageable.
4. Re-enable the workflow.

**Comment by vgvassilev** [comment]
cc: @GabrielDosReis

**Comment by quinnlp** [comment]
Hello, we wanted to state our needs as an interested customer. At Intel we are interested in this effort because we need `LLVM_BUILD_DYLIB` support for Windows to enable Windows support for [triton-ext](https://github.com/triton-lang/triton-ext/), which is a framework for developing Triton compiler extensions. We also need support for building MLIR as a DYLIB.

CC @etiotto, @whitneywhtsang

**Comment by abrown** [comment]
Same as above; this could be helpful for triton-ext. In talking this over with @compnerd the other day, I got a sense of the scale of the problem and the concerns for ongoing maintenance, but it still seems like a worthwhile effort. Thanks for working on this!

**Comment by robert-neuville** [comment]
Hi,

I'm also interested in a good support of LLVM_BUILD_DYLIB on Windows, as it is the solution of many issues we have while working with out of tree LLVM plugins.

I have a good background of Windows applications and DLL plugins development, so the "symbol export hell" sounds familiar to me.

I could help, but I don't really know where to start as my knowledge on the LLVM source code is very limited.

Is there any resources taht I can read on the "current" export strategy which leads to too many symbols and the "future" export strategy which should lead to export only needed symbols ?

**Comment by mcbarton** [comment]
@Steelskin Is this LLVM_ABI annotation supposed to be there in clang https://github.com/llvm/llvm-project/blob/8c51f24e7469069137a96c4daf6cd975d0a98e35/clang/lib/CodeGen/BackendUtil.cpp#L125 ? It seems out of place, and my understanding at least is that clang would be using its own abi annotations and not be reliant on the LLVM one.

**Comment by Steelskin** [comment]
> @Steelskin Is this LLVM_ABI annotation supposed to be there in clang https://github.com/llvm/llvm-project/blob/8c51f24e7469069137a96c4daf6cd975d0a98e35/clang/lib/CodeGen/BackendUtil.cpp#L125 ? It seems out of place, and my understanding at least is that clang would be using its own abi annotations and not be reliant on the LLVM one.

This is counterintuitive but this is an extern declaration in the `clang` directory. The `ProfileCorrelate` global is defined in the core LLVM library in `InstrProfiling.cpp` and is exported from `LLVM-<version>.dll` https://github.com/llvm/llvm-project/blob/bb0eada255b31e341d8843f26757f45fdf48b301/llvm/lib/Transforms/Instrumentation/InstrProfiling.cpp#L76


The declaration of `ProfileCorrelate` in `BackendUtil.cpp` must match its original definition in `InstrProfiling.cpp`, hence the same `LLVM_ABI` annotation. Since this is compiled in the consumer library, `LLVM_ABI` should expand to `__declspec(dllimport)` when compiled for the LLVM dynamic library build.

**Comment by danilaml** [comment]
Btw, one failure I've seen trying to check out dylib on window sis that tablegen failed with unresolved symbol to `SubtargetFeatures` constructor in https://github.com/llvm/llvm-project/blob/main/llvm/utils/TableGen/Basic/TargetFeaturesEmitter.cpp because it includes `"llvm/TargetParser/SubtargetFeature.h"`  for its `MAX_SUBTARGET_FEATURES` constants but this introduces a cyclic dependency between libraries and linker errors on Windows. Not sure if the current tooling can catch and handle those.

**Comment by fsfod** [comment]
is it happening for full tablegen or llvm-min-tblgen?

**Comment by danilaml** [comment]
Only checked with `llvm-min-tblgen`. Applied local workaround ("inlined" constants) and got some similar error later (on vector destructor or something for a different lib) after which I've switch back to static.

**Comment by Steelskin** [comment]
@danilaml Could you let me know how you are invoking the build? I know of a couple of issues with the build on main right now, which I am working toward fixing.

**Comment by danilaml** [comment]
@Steelskin nothing special. Just using `cmake --build` with the build configured via the following preset:
```json
            "generator": "Ninja",
            "cacheVariables": {
                "LLVM_BUILD_LLVM_DYLIB_VIS": "ON",
                "LLVM_ENABLE_LIBXML2": "OFF",
                "LLVM_TARGETS_TO_BUILD": "X86;AArch64",
                "LLVM_LINK_LLVM_DYLIB": "ON",
                "LLVM_BUILD_GLOBAL_ISEL": "OFF",
                "CMAKE_EXPORT_COMPILE_COMMAND": "1",
                "LLVM_ENABLE_ASSERTIONS": "ON",
                "LLVM_OPTIMIZED_TABLEGEN": "ON",
                "CMAKE_BUILD_TYPE": "RelWithDebInfo",
                "CMAKE_C_COMPILER": "cl",
                "CMAKE_CXX_COMPILER": "cl"
            }
```

**Comment by Steelskin** [comment]
@danilaml I think the main issue you are hitting right now is that the PCH+dylib build is broken. I am working on a fix for it.

**Comment by danilaml** [comment]
@Steelskin are PCH enabled by default on windows? I don't remember enabling it explicitly.

**Comment by aengelke** [comment]
Yes, PCH is on by default, except with GCC, on AIX, on S390, with Clang <18, with sccache, and with ccache+non-Clang.

**Comment by Steelskin** [comment]
@danilaml Yes it's on be default as previously mentioned. If you want to try the dylib build, you should also set these for now:
```
-D CMAKE_DISABLE_PRECOMPILE_HEADERS=OFF
-D CLANG_LINK_CLANG_DYLIB=OFF
```

The first disables PCH and the second disables the libclang dylib, which is not currently functional. I am working toward a fix for dylib+PCH.

**Comment by paperchalice** [comment]
Can I expect LLVM 23 to be buildable as a dynamic library using MSVC?

Update:
I can build it with:
- Cherry-pick 5018aebcde6bcb3a29e3e10bd332865289e01e29
- Add `#include "llvm/Support/VirtualFileSystem.h"` in `llvm/include/llvm/Transforms/IPO/Instrumentor.h`
- Remove `LLVM_ABI` before `Error extractLTOInputs();` in `llvm/include/llvm/DTLTO/DTLTO.h`

**Comment by Steelskin** [comment]
> Can I expect LLVM 23 to be buildable as a dynamic library using MSVC?

No, but I am hoping that you will be able to with LLVM 24.
