### ISSUE TITLE
[Flang][OpenMP] Important issues to be fixed prior to removing experimental status of OpenMP

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#110008]
### TODOs for unsupported OpenMP 5.2 features

- [x] conditional modifier for lastprivate   https://github.com/llvm/llvm-project/pull/110568
- [x] iterator modifier for affinity, depend, from, map, to (@kparzysz)
- [x] scan directive :  https://github.com/llvm/llvm-project/pull/102792 @anchuraj 
- [x] inscan modifier for reduction (@Leporacanthicus)
- [x] task modifier for reduction clause (@Leporacanthicus)
- [x] in_reduction clause for task and target (@Leporacanthicus)
- [x] task_reduction clause for taskgroup (@Leporacanthicus)
- [x] reduction, in_reduction clause for taskloop (@kaviya2510)  https://github.com/llvm/llvm-project/pull/139704
- [x] close, present, ompx_hold map-type modifiers for map clause (@kparzysz) https://github.com/llvm/llvm-project/pull/111860
- [x] none parameter for defaultmap clause (Currently caught in Semantics giving an error - leaving as is for now @Leporacanthicus)
- [x] declare mapper directive @Leporacanthicus https://github.com/llvm/llvm-project/pull/115160
- [x] metadirective (@kparzysz)
  - [x] https://github.com/llvm/llvm-project/pull/122900
  - [x] https://github.com/llvm/llvm-project/pull/121817 (approved)
  - [x] https://github.com/llvm/llvm-project/pull/123243
  - [x] https://github.com/llvm/llvm-project/pull/123397 (approved)
  - [x] https://github.com/llvm/llvm-project/pull/124278
- [x] declare variant directive : ARM @kiranchandramohan WIP https://github.com/llvm/llvm-project/pull/130578
- [x] collapse of imperfectly nested loops for simd, worksharing, distribute and taskloop. Currently there is a semantics error.
- [x] affinity clause for task (@kparzysz) https://github.com/llvm/llvm-project/pull/113485
- [x] detach clause for task (@NimishMishra): https://github.com/llvm/llvm-project/pull/112312, https://github.com/llvm/llvm-project/pull/116601, https://github.com/llvm/llvm-project/pull/119128, https://github.com/llvm/llvm-project/pull/119172
- [x] cancel construct : support for taskloop (@kiranktp )
- [x] mutexinoutset for depend clause (@kparzysz) https://github.com/llvm/llvm-project/pull/114895
- [x] ancestor modifier for device clause of target construct
- [x] depend and nowait clause for taskwait (@Leporacanthicus)
- [x] acq_rel, acquire, release clauses for atomic construct
- [x] depend clause extensions to support iterators and depend objects with depobj construct (@kparzysz) https://github.com/llvm/llvm-project/pull/113622, https://github.com/llvm/llvm-project/pull/114074
- [x] Combined constructs master taskloop, parallelmaster, parallel master taskloop, master taskloop simd, parallel master taskloop simd @kiranchandramohan https://github.com/llvm/llvm-project/pull/113893
- [x] iterators in map clause and data motion clauses of target update (@kparzysz)
- [x] present argument for defaultmap ( @agozillon )
- [x] align clause on allocate directive : ARM https://github.com/llvm/llvm-project/pull/120791
- [x] allocator and align modifiers for allocate clause : ARM https://github.com/llvm/llvm-project/pull/121356
- [x] adjust_args and append_args clauses for declare variant directive : ARM
- [x] dispatch construct : https://github.com/llvm/llvm-project/pull/121982 @Leporacanthicus 
- [x] Assumption directives : https://github.com/llvm/llvm-project/pull/120770 @Leporacanthicus 
- [x] nothing directive (@kparzysz) https://github.com/llvm/llvm-project/pull/120606
- [x] error directive : ARM   https://github.com/llvm/llvm-project/pull/119582
- [ ] Loop transformation constructs. The parsing of these constructs work and a TODO is emitted, but semantic checks should be updated to allow loop transformation constructs in place of Fortran do loops. @Stylie777 
- [x] scope directive @kiranchandramohan https://github.com/llvm/llvm-project/pull/113700
- [x] strict modifier for grainsize and num_tasks clause @kiranchandramohan https://github.com/llvm/llvm-project/pull/113136
- [x] thread_limit clause for target directive. Frontend and Lowering support is present. Translation support is probably missing (@skatrak).
- [x] has_device_addr clause for target construct. Frontend and Lowering support is present. Translation support is probably missing. (@kparzysz) https://github.com/llvm/llvm-project/pull/128568
- [x] interop directive : [Swateesh- AMD] https://github.com/llvm/llvm-project/pull/120584
- [x] compare, fail clauses : ARM Compare support: https://github.com/llvm/llvm-project/pull/117032 and 1https://github.com/llvm/llvm-project/pull/18683
- [x] seq_cst clause for flush construct https://github.com/llvm/llvm-project/pull/114072
- [x] inoutset argument for depend clause (@kparzysz) https://github.com/llvm/llvm-project/pull/114895
- [x] Allow copyprivate, nowait on the directive (in addition to end directive) (@Thirumalai-Shaktivel, https://github.com/llvm/llvm-project/pull/127769)
- [x] Deprecation of destroy with depobj (@kparzysz) https://github.com/llvm/llvm-project/pull/114988
- [x] step modifier for linear. Deprecation (@kparzysz) https://github.com/llvm/llvm-project/pull/119278
- [x] Deprecation of modifiers without comma separators (@kparzysz) https://github.com/llvm/llvm-project/pull/117447
- [x] enter as synonym for to clause in declare target . to clause is deprecated. @Stylie777 https://github.com/llvm/llvm-project/pull/143505
- [x] declare mapper directive extension to accept iterator-modifier and the present map-type-modifier (@kparzysz) https://github.com/llvm/llvm-project/pull/144359
- [x] allocators construct. allocate directive for ALLOCATE statement is deprecated : @Stylie777 https://github.com/llvm/llvm-project/pull/142378
- [x] dispatch construct has optional end directive : @Leporacanthicus https://github.com/llvm/llvm-project/pull/121982
- [x] otherwise clause as synonym for default on metadirective (@kparzysz) (https://github.com/llvm/llvm-project/pull/121817)
- [x] allocate and firstprivate for scope directive : ARM (@Leporacanthicus) https://github.com/llvm/llvm-project/pull/116801
- [x] target enter and exit data has default map type : @Stylie777 https://github.com/llvm/llvm-project/pull/144715
- [x] doacross clause as synonym for depend in some situations (@kparzysz) https://github.com/llvm/llvm-project/pull/115396 https://github.com/llvm/llvm-project/pull/115397

### TODOs for unsupported OpenMP 4.0 features
- [x] declare reduction @Leporacanthicus 

### Must fix issues from the tracker
A subset of issues from https://github.com/llvm/llvm-project/issues?q=is%3Aopen+is%3Aissue+label%3Aflang%3Aopenmp
- [x] Atomic with array constructor https://github.com/llvm/llvm-project/issues/104526 @Thirumalai-Shaktivel https://github.com/llvm/llvm-project/pull/121181
- [x] Atomic write to complex https://github.com/llvm/llvm-project/issues/113479 @NimishMishra  https://github.com/llvm/llvm-project/pull/121055
- [x] Error when capture-statement described in atomic capture construct contains a different type https://github.com/llvm/llvm-project/issues/115652  @NimishMishra : https://github.com/llvm/llvm-project/pull/121055
- [x] Runtime segfault when allocatable threadprivate variable is used with copyin https://github.com/llvm/llvm-project/issues/113191 @kaviya2510 : https://github.com/kaviya2510/llvm-project/tree/copyin_allocatable
- [x] Assertion failure using default clause with critical https://github.com/llvm/llvm-project/issues/112572
- [x] Crash in OpenMPIRBuilder when trying to outline a parallel region with an infinite loop https://github.com/llvm/llvm-project/issues/112884 @tblah
- [x] Problem building GAMESS (delayed privatisation of derived type) https://github.com/llvm/llvm-project/issues/109727
- [x] dot product inside of omp.parallel (part of cp2k) https://github.com/llvm/llvm-project/issues/116954
- [x] Privatisation with sections ICE https://github.com/llvm/llvm-project/issues/135108 @tblah
- [x] Common block name in omp flush https://github.com/llvm/llvm-project/issues/136583 @tblah
- [x] threadprivate with pointer to character https://github.com/llvm/llvm-project/issues/108136 @tblah
- [x] https://github.com/llvm/llvm-project/issues/140754 @mrkajetanp https://github.com/llvm/llvm-project/pull/142415
- [x] https://github.com/llvm/llvm-project/issues/140741 @mrkajetanp https://github.com/llvm/llvm-project/pull/142160
- [x] https://github.com/llvm/llvm-project/issues/140732 @mrkajetanp https://github.com/llvm/llvm-project/pull/142783
- [x] https://github.com/llvm/llvm-project/issues/139071 @kparzysz https://github.com/llvm/llvm-project/pull/144593
- [x] https://github.com/llvm/llvm-project/issues/138436 @tblah https://github.com/llvm/llvm-project/pull/142997
- [x] https://github.com/llvm/llvm-project/issues/138102 @mrkajetanp https://github.com/llvm/llvm-project/pull/145051
- [x] https://github.com/llvm/llvm-project/issues/133685 @tblah https://github.com/llvm/llvm-project/pull/140798
- [x] https://github.com/llvm/llvm-project/issues/133678 @mrkajetanp https://github.com/llvm/llvm-project/pull/142595
- [x] https://github.com/llvm/llvm-project/issues/126451
- [x] https://github.com/llvm/llvm-project/issues/116428
- [x] https://github.com/llvm/llvm-project/issues/142365 @tblah https://github.com/llvm/llvm-project/pull/143112
- [x] https://github.com/llvm/llvm-project/issues/142404 @tblah https://github.com/llvm/llvm-project/pull/143907
- [x] https://github.com/llvm/llvm-project/issues/142123 @mrkajetanp https://github.com/llvm/llvm-project/pull/144092
- [x] https://github.com/llvm/llvm-project/issues/142935
- [x] https://github.com/llvm/llvm-project/issues/143231 @tblah https://github.com/llvm/llvm-project/pull/144502
- [x] https://github.com/llvm/llvm-project/issues/143229 @tblah https://github.com/llvm/llvm-project/pull/144040
- [x] https://github.com/llvm/llvm-project/issues/144178 @tblah

### Must fix issues not in tracker

- [x] Default loop schedule modifier for worksharing-loop constructs without static schedule and ordered clause is nonmonotonic since OpenMP 5.0 @tblah
- [x] Privatization issues in interfacing with OpenMPIRBuilder. https://discourse.llvm.org/t/rfc-openmp-fix-issue-in-mlir-to-llvmir-translation-for-delayed-privatisation/81225. Fixed by @tblah https://github.com/llvm/llvm-project/pull/111844
- [x] Support for deferred task execution @tblah https://github.com/llvm/llvm-project/pull/125307

Minor bugs:
- [x] Crash with undeclared variable and `implicit none`:  https://github.com/llvm/llvm-project/issues/131655
- [x] Bad word ordering leads to assert in lowering: https://github.com/llvm/llvm-project/issues/131659

**Comment by anchuraj** [comment]
`inscan` modifier support is WIP

**Comment by kiranchandramohan** [comment]
> `inscan` modifier support is WIP

Feel free to update the tasklist if you or someone you know is working on it. The immediate requirement is to only add a TODO message after parsing and semantics.

**Comment by kiranchandramohan** [comment]
> > TODOs for unsupported OpenMP 5.2 features
> 
> I find it strange that a standard version released after flang got merged into LLVM is somehow a deciding factor for whether the whole compiler is considered incomplete or experimental.
> 
> It sounds like massive scope creep, in the sense that, when flang was proposed for inclusion, no-one could have required an unreleased standard as the benchmark for what counts as a full-fledged fortran compiler.

We started with OpenMP 4.5 standard when it was the F18 project. Subsequently, we have added OpenMP 5.2 features to the implementation. What I would like to get to is to be able to make statements on what is supported and what is not supported. Since some OpenMP 5.2 features are added the only standard that we can aim to completely address is OpenMP 5.2.

Also, I am not saying we have to support all OpenMP 5.2 features. The requirement is only to issue messages and gracefully error that the feature is not supported as the rest of the compiler says for Fortran language features. Also, this is not a requirement for the whole of the compiler, it is only about the experimental nature of the OpenMP implementation.
Note: I will change the title of the ticket to reflect this.

**Comment by Leporacanthicus** [comment]
Additional tests and small OpenMP.cpp changes available to review here:
https://github.com/llvm/llvm-project/pull/111562

I will continue this work, but this seemed like a good place to stop for today, and may start reviewing this part.

**Comment by tblah** [comment]
Should we also include fixing (at least some) compiler crash tickets before removing the experimental warning?

**Comment by kiranchandramohan** [comment]
> Should we also include fixing (at least some) compiler crash tickets before removing the experimental warning?

If there are important issues please add it to the following entry.

> ### Must fix issues from the tracker

**Comment by tblah** [comment]
> If there are important issues please add it to the following entry. 

I have added some, striking an opinionated balance between adding the whole issue tracker and missing important issues. If others disagree with my prioritization of those issues or would like to add more please go ahead.

**Comment by kiranchandramohan** [comment]
> > If there are important issues please add it to the following entry.
> 
> I have added some, striking an opinionated balance between adding the whole issue tracker and missing important issues. If others disagree with my prioritization of those issues or would like to add more please go ahead.

I have moved it to the `Must fix issues from the tracker` section.

**Comment by anchuraj** [comment]
reduction modifier MLIR support under review:  https://github.com/llvm/llvm-project/pull/114737

**Comment by agozillon** [comment]
I would like to claim: "present argument for defaultmap" from the 5.2 list, I've started a bit of work towards supporting defaultmap and i'll finish it up in the nearish future once I can spare a bit more time towards it :-)
