### ISSUE TITLE
Structured buffers

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#113512]
- [x] llvm/llvm-project#106189
- [ ] llvm/llvm-project#112775
- [ ] llvm/llvm-project#112776
- [ ] llvm/llvm-project#112777
- [ ] llvm/llvm-project#112977
- [ ] llvm/wg-hlsl#87
- [ ] llvm/llvm-project#112968
- [ ] llvm/llvm-project#112984
- [ ] llvm/llvm-project#106188
- [ ] llvm/llvm-project#92147
- [ ] llvm/llvm-project#112982
