### ISSUE TITLE
Tracking issue for removing PDB plugin in LLDB

### ISSUE THREAD

**Issue by ZequanWu** [llvm/llvm-project#114906]
This is to track the progress of fixing all failed tests when only using native PDB plugin (`-DLLVM_ENABLE_DIA_SDK=NO`).

Currently, there are 12 failed tests and 1 unexpected passed tests.
```
Failed Tests (12):
  lldb-shell :: Expr/nodefaultlib.cpp
  lldb-shell :: SymbolFile/DWARF/dwo-static-data-member-access.test
  lldb-shell :: SymbolFile/PDB/class-layout.test
  lldb-shell :: SymbolFile/PDB/enums-layout.test
  lldb-shell :: SymbolFile/PDB/expressions.test
  lldb-shell :: SymbolFile/PDB/func-symbols.test
  lldb-shell :: SymbolFile/PDB/pointers.test
  lldb-shell :: SymbolFile/PDB/type-quals.test
  lldb-shell :: SymbolFile/PDB/typedefs.test
  lldb-shell :: SymbolFile/PDB/udt-layout.test
  lldb-shell :: SymbolFile/PDB/variables.test
  lldb-shell :: Unwind/windows-unaligned-x86_64.test

********************
Unexpectedly Passed Tests (1):
  lldb-shell :: Commands/command-disassemble-mixed.c
```

Here are the causes for those failed tests:
- [ ] No decl information for record types and functions: `class-layout.test`, `enums-layout.test`, `func-symbols.test`, `pointers.test`
- [ ] #51933: `expressions.test`
- [ ] Some types not showing up in Types under lldb-test: `pointers.test`, `type-quals.test`, `typedefs.test`
- [ ] Crash with Assertion failed: D->isCompleteDefinition() && "Cannot layout type before complete!": `udt-layout.test`
- [ ] Native PDB doesn't showing block inside function when dumping symbols with lldb-test: `variables.test`
- [ ] Other: `windows-unaligned-x86_64.test`, `nodefaultlib.cpp`, `dwo-static-data-member-access.test`

Once those tests are fixed, we might be able to proceed with removing PDB plugin.

**Comment by Nerixyz** [comment]
> I don't think LLVM is making use of [`lf_alias`](https://github.com/microsoft/microsoft-pdb/blob/805655a28bd8198004be2ac27e6e0290121a5e89/include/cvinfo.h#L895) which is the type stream node for typedefs.

MSVC doesn't seem to emit this either. Compiling https://github.com/llvm/llvm-project/blob/04f98889ae497d895be7c478415e0e9a8c6d330b/lldb/test/Shell/SymbolFile/PDB/Inputs/SimpleTypesTest.cpp with MSVC and dumping the PDB (with llvm's dump, cvdump, and MS's rust version) doesn't show any `LF_ALIAS`. Do you have an example where Clang/LLVM doesn't generate this, but MSVC does?

> `SymbolFileNativePDB::FindType` (called by the front-end SB stuff for type lookups) only looks in the type stream.

From what I can tell, C typedefs are emitted as `S_UDT`. LLDB does parse these in [`ParseTypes`](https://github.com/llvm/llvm-project/blob/7cd1ce3aa006424d20e95a2a4fe7df7113527976/lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp#L1796). Still looks like something is wrong with that.

To be able to find these in `FindTypes`, we'd need to walk the globals stream. We could probably cache this after the first call.

**Comment by Walnut356** [comment]
>MSVC doesn't seem to emit this either.

Tbh, i'm not sure if MSVC is right or wrong in this case. The node exists, it's labeled for use to designate typedefs, but then the original codeview spec also lists the udt node for typedefs. In my eyes, the fact that they went out of their way to make a specialized one means it should probably be used when possible, and downstream consumers (e.g. `TypeSystem`) would absolutely benefit from being able to tell what's a typedef and what's not. There are other instances of nodes not being used by MSVC when they probably should, such as the [`TaggedUnion`](https://learn.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/udtkind?view=vs-2022) UDT kind, which specifically notes its use in Rust, but is never actually emitted for Rust code afaik.

>From what I can tell, C typedefs are emitted as S_UDT.

I should specify, I'm mainly coming from a Rust perspective. Rust outputs [msvc-style](https://github.com/rust-lang/rust/blob/e1b9081e699065badfc1a9419ec9566e5c8615c4/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs#L666) primitive names (that disappear because codeview doesn't have a `name` field for primitives anyway), and then wraps them in a [typedef with the Rust-style name (e.g. `u8`)](https://github.com/rust-lang/rust/blob/e1b9081e699065badfc1a9419ec9566e5c8615c4/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs#L804). These typedefs appear in the symbol stream, but there is no UDT (or any other type-stream node) with type name `u8` that I can find. 

For what it's worth, I tried manually wrapping pointer/ref nodes in structs a while ago so that the UDT node would be guaranteed to exist and be attached to the local variable. It worked on my end (on `windows-msvc`, `windows-gnu`, and `linux-gnu`) but CI gave [cryptic errors about broken modules](https://github.com/rust-lang/rust/pull/136080) so iunno.

Later today I can look into the C side of things a bit more. I did some tests comparing C and Rust output a few months ago and I remember there being similar issues with typedefs between the two, but I don't remember well enough to say anything definitive.

>LLDB does parse these in [ParseTypes](https://github.com/llvm/llvm-project/blob/7cd1ce3aa006424d20e95a2a4fe7df7113527976/lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp#L1796).

afaict `ParseTypes` is only called via `Module::ParseAllDebugSymbols`, and I don't think that ends up called as a result of the `type lookup` command, nor is it it called via `SBModule::FindFirstType`.  

`msdia` is still able to snag some of them during regular processing, as evidenced by [this PR actually working](https://github.com/rust-lang/rust/pull/144394#issue-3259664510), but there's also still no way to associate those typedefs with local variables. I checked via a PDB dump, and even with pointers getting `ref$<u8>` typedefs, there's nothing discoverable by that name in the type stream. I'd test it with the native pdb parser, but it's currently broken for Rust i think? It looks like it's using the unique ID as the type name instead of the name field so the output isn't super helpful lol

Native:

<img width="562" height="51" alt="Image" src="https://github.com/user-attachments/assets/c80e7b89-f48c-4cec-af3b-cd42d4c9508c" />

Dia:

<img width="417" height="89" alt="Image" src="https://github.com/user-attachments/assets/19fe08e3-f06c-4f57-9e25-fccde0cc9d67" />

**Comment by Nerixyz** [comment]
> In my eyes, the fact that they went out of their way to make a specialized one means it should probably be used when possible, and downstream consumers (e.g. `TypeSystem`) would absolutely benefit from being able to tell what's a typedef and what's not.

Through `S_UDT`, the symbol file can already tell if something is a typedef. Maybe I'm missing something here.

> afaict `ParseTypes` is only called via `Module::ParseAllDebugSymbols`, and I don't think that ends up called as a result of the `type lookup` command, nor is it it called via `SBModule::FindFirstType`.

Oh yeah, I was referring to the `typedefs.test` which parses all types.

> but there is no UDT (or any other type-stream node) with type name `u8` that I can find.

Compiling a small Rust program yields UTDs for u8, u16, u32, and u64.

> I'd test it with the native pdb parser, but it's currently broken for Rust i think? It looks like it's using the unique ID as the type name instead of the name field so the output isn't super helpful lol

I don't think there's an issue for this yet - not sure what the best approach would be because `UniqueName` yields consistent type names for C++. Would be great to get this fixed.

---

Are you compiling LLDB by yourself? If so, you could try https://github.com/Nerixyz/llvm-project/commit/745d749f5404b0bea23f54451fe378778bd1aa06. This should resolve types that are specified by `S_UDT`.

Either way, this discussion feels a bit too specific for this issue. So it might be good to make a sub-issue for typedef/`S_UDT`/`LF_ALIAS`.

**Comment by Walnut356** [comment]
>Through S_UDT, the symbol file can already tell if something is a typedef. Maybe I'm missing something here.

[Local variables store their type via a type index](https://github.com/microsoft/microsoft-pdb/blob/805655a28bd8198004be2ac27e6e0290121a5e89/include/cvinfo.h#L4193), this is also true for [global variables](https://github.com/microsoft/microsoft-pdb/blob/805655a28bd8198004be2ac27e6e0290121a5e89/include/cvinfo.h#L3632). Since typedef nodes don't live in the type stream, variables cannot have typedefs as types.

The front-end asks the `TypeSystem` about the type of a variable, but the `TypeSystem` and `SymbolFile` can't tell the difference between an `unsigned char` and a `uint8_t` because the actual type-node referenced by the variable will always be the underlying raw `unsigned char` node.

I don't know exactly how the test is failing, or exactly how the test file is executed, but if it ever tries to check if a local or global variable has a typedef-type, it will always fail with the way things currently are. If typedefs were also generated in the type stream via `lf_alias` (equivalent to dwarf's `DW_TAG_typedef`), variables could references those nodes directly and typedefs would appear properly in the front-end. 

>Compiling a small Rust program yields UTDs for u8, u16, u32, and u64.

My b, I conflated the UDT symbol node and the `Class` type node. UDT nodes are generated for typedefs, but the above problem will exist so long as typedefs only live in symbol nodes.

**Comment by DavidSpickett** [comment]
We have been discussing this in https://discourse.llvm.org/t/rfc-removing-the-dia-pdb-plugin-from-lldb/87827 and have concluded that we still want to remove the DIA plugin eventually. With the first step being to make native the default.

This issue started with a list of failing tests, so here's the current state of things.

First results from @Nerixyz on x86_64 (from https://discourse.llvm.org/t/rfc-removing-the-dia-pdb-plugin-from-lldb/87827/20):

> Sure, there are still 12 failures (x86, but a few different ones):
> 
> * Settings/TestFrameFormatFunctionReturnObjC.test (new) and SymbolFile/DWARF/dwo-static-data-member-access.test (known)  
>   breakpoint set \-n \<name\> doesn’t work with the native plugin(?). Might be because AddSymbols isn’t implemented yet ([\[LLDB\]\[NativePDB\] Implement \`AddSymbols\` by Nerixyz · Pull Request \#154121 · llvm/llvm-project · GitHub](https://github.com/llvm/llvm-project/pull/154121)). Though for the second test, it’s unexpected that this runs with PDB on Windows in the first place.  
> * SymbolFile/PDB/expressions.test (known)  
>   Can’t find static variable in namespace.  
> * SymbolFile/PDB/func-symbols.test (known)  
>   Argument and return types are not created by the native plugin.  
> * SymbolFile/PDB/function-nested-block.test (known)  
>   In the DIA plugin, the main function is found as ‘name \= “main”, mangled \= “main”’ but in the native plugin, there’s no mangled name.  
> * SymbolFile/PDB/native-setting.cpp (new)  
>   This fails because there’s no DIA plugin. So the native plugin is always used. Maybe there should be an additional REQUIRES for DIA support?  
> * SymbolFile/PDB/pointers.test (known)  
>   Fails because function types in the native plugin don’t have a name. The DIA plugin created the function types with a name. For example, int foo(int) would create a Type{...} name="foo" compiler\_type \= ... int (int). The native plugin creates Type{...} compiler\_type \= ... int (int).  
>   Furthermore, the native plugin doesn’t include any blocks and their variables.  
> * SymbolFile/PDB/type-quals.test (known)  
>   Same reason as SymbolFile/PDB/func-symbols.test  
> * SymbolFile/PDB/typedefs.test (known)  
>   Fails because the native plugin creates typedefs with the typedef’d type. So typedef char MyChar would show as Type{..} , name \= "MyChar", size \= 1, compiler\_type \= char whereas DIA would show ... compiler\_type \= typedef MyChar. Seems like a simple fix.  
> * SymbolFile/PDB/udt-layout.test (known)  
>   This hits an assertion failure, because it tries to print a static whose type doesn’t have a layout through target variable. It’s a type from the CRT that is forward declared without a complete definition.  
> * SymbolFile/PDB/variables.test (known)  
>   Fails because functions don’t have a mangled name yet (might be more failures after that).  
> * Unwind/windows-unaligned-x86\_64.test (known)  
>   The symbols for the assembly functions are not found.
> 
> SymbolFile/PDB/class-layout.test and SymbolFile/PDB/enums-layout.test are no longer failing.

I did the same on Windows on Arm (https://discourse.llvm.org/t/rfc-removing-the-dia-pdb-plugin-from-lldb/87827/21) and got the same results when we ignore the x86_64 specific tests, and a toolchain issue in my local env. Plus 1 unexpected pass.
```
********************
Failed Tests (12):
  lldb-shell :: BuildScript/toolchain-msvc.test    <<<< (due to my local environment)
  lldb-shell :: Settings/TestFrameFormatFunctionReturnObjC.test
  lldb-shell :: SymbolFile/DWARF/dwo-static-data-member-access.test
  lldb-shell :: SymbolFile/PDB/expressions.test
  lldb-shell :: SymbolFile/PDB/func-symbols.test
  lldb-shell :: SymbolFile/PDB/function-nested-block.test
  lldb-shell :: SymbolFile/PDB/native-setting.cpp
  lldb-shell :: SymbolFile/PDB/pointers.test
  lldb-shell :: SymbolFile/PDB/type-quals.test
  lldb-shell :: SymbolFile/PDB/typedefs.test
  lldb-shell :: SymbolFile/PDB/udt-layout.test
  lldb-shell :: SymbolFile/PDB/variables.test

********************
Unexpectedly Passed Tests (1):
  lldb-shell :: Commands/command-disassemble-mixed.c
```

So we have a couple of things fixed, a couple of new failures and the same UPASS as seen before.

**Comment by ZequanWu** [comment]
> With the native plugin, lldb-test wouldn't show function blocks and variables. However, the plugin does create the same blocks and variables as the DIA plugin.

But why it works with dwarf plugin.

> The other reason is that the native plugin specifies the location differently.

We should just update it to adopt NativePDB's output for variable location because it is more accurate. Each variable location is a `DWARFExpressionList` which is a list with ranges, each has their own DWARFExpression (specifying the variable location within that range).

**Comment by ZequanWu** [comment]
> > With the native plugin, lldb-test wouldn't show function blocks and variables. However, the plugin does create the same blocks and variables as the DIA plugin.
> 
> But why it works with dwarf plugin.
> 
> >

I see, it's because `symbols->ParseVariablesForContext(sc);` is called before `symbols->ParseBlocksRecursive(*f);` and NativePDB's parse local variable function doesn't call `GetBlock(true)` to set the flag. Maybe we should just explicitly call `SetBlockInfoHasBeenParsed` in `SymbolFileNativePDB::ParseBlocksRecursive` because we know all children blocks are parsed at the end of `ParseBlocksRecursive`.
