### ISSUE TITLE
Clang C++20 Feature: Declarations and where to find them

### ISSUE THREAD

**Issue by cor3ntin** [llvm/llvm-project#54150]
Paper link: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1787r6.html

This fixes a number of DRs, I think a first order of business would be to understand what changes are actually needed in clang

**Comment by frederick-vs-ja** [comment]
I'm adding DR status in Clang's implementation staus page (#68846). Do you think we should specially list P1787R6 (which is effectively a DR) in that page or track resolved issues in the page for CWG issues?

**Comment by AaronBallman** [comment]
CC @Endilll who has also been working on conformance tests in this area.

Personally, I think it's more helpful to track the individual resolved issues than it is to track status of the omnibus paper fixing them; I expect the paper's status will be `Partial` for approximately... ever.

**Comment by Endilll** [comment]
Here is status for **tests** (checkbox) and availability (in parentheses) in the order [P1787R6](https://wg21.link/p1787r6) describes them. N/A are marked as having tests, since no work is due for them. I'm also listing only defect reports, omitting unresolved Core issues.

### Definitions
- [x] (N/A) [CWG554](https://cplusplus.github.io/CWG/issues/554.html) Definition of “declarative region” and “scope”
- [x] (N/A) [CWG2165](https://cplusplus.github.io/CWG/issues/2165.html) Namespaces, declarative regions, and translation units
- [x] (Yes) [CWG405](https://cplusplus.github.io/CWG/issues/405.html) Unqualified function name lookup
- [x] (Yes) [CWG36](https://cplusplus.github.io/CWG/issues/36.html) _using-declarations_ in multiple-declaration contexts
- [x] (No) [CWG418](https://cplusplus.github.io/CWG/issues/418.html) Imperfect wording on error on multiple default arguments on a called function
- [x] (No) [CWG1960](https://cplusplus.github.io/CWG/issues/1960.html) Visibility of entity named in class-scope _using-declaration_
- [x] (N/A) [CWG1291](https://cplusplus.github.io/CWG/issues/1291.html) Looking up a _conversion-type-id_
- [x] (No) [CWG2396](https://cplusplus.github.io/CWG/issues/2396.html) Lookup of names in complex _conversion-type-id_s
- [x] (Yes) [CWG600](https://cplusplus.github.io/CWG/issues/600.html) Does access control apply to members or to names?
- [x] (Yes) [CWG360](https://cplusplus.github.io/CWG/issues/360.html) Using-declaration that reduces access
- [x] (Yes) [CWG952](https://cplusplus.github.io/CWG/issues/952.html) Insufficient description of “naming class”

### Lookup completeness
- [x] (Yes) [CWG191](https://cplusplus.github.io/CWG/issues/191.html) Name lookup does not handle complex nesting
- [x] (N/A) [CWG1200](https://cplusplus.github.io/CWG/issues/1200.html) Lookup rules for template parameters
- [x] (N/A) [CWG536](https://cplusplus.github.io/CWG/issues/536.html) Problems in the description of _id-expressions_
- [x] (Clang 11) [CWG399](https://cplusplus.github.io/CWG/issues/399.html) Destructor lookup redux
- [x] (N/A) [CWG562](https://cplusplus.github.io/CWG/issues/562.html) _qualified-ids_ in non-expression contexts
- [x] (No) [CWG2370](https://cplusplus.github.io/CWG/issues/2370.html) `friend` declarations of namespace-scope functions
- [x] (Yes) [CWG1822](https://cplusplus.github.io/CWG/issues/1822.html) Lookup of parameter names in _lambda-expressions_
- [x] (Clang 3.8) [CWG1894](https://cplusplus.github.io/CWG/issues/1894.html) _typedef-name_s and _using-declaration_s
- [x] (Clang 3.8) [CWG2199](https://cplusplus.github.io/CWG/issues/2199.html) Typedefs and tags
- [x] (Yes) [CWG607](https://cplusplus.github.io/CWG/issues/607.html) Lookup of _mem-initializer-id_s
- [x] (Clang 3.3) [CWG1837](https://cplusplus.github.io/CWG/issues/1837.html) Use of `this` in `friend` and local class declarations
- [x] (Clang 3.4) [CWG2007](https://cplusplus.github.io/CWG/issues/2007.html) Argument-dependent lookup for `operator=`
- [x] (Yes) [CWG255](https://cplusplus.github.io/CWG/issues/255.html) Placement deallocation functions and lookup ambiguity

### Complete-class context
- [x] (N/A) [CWG2331](https://cplusplus.github.io/CWG/issues/2331.html) Redundancy in description of class scope
- [x] (N/A) [CWG2009](https://cplusplus.github.io/CWG/issues/2009.html) Unclear specification of class scope

### Declaration matching
- [x] (Yes) [CWG1821](https://cplusplus.github.io/CWG/issues/1821.html) Qualified redeclarations in a class _member-specification_
- [x] [CWG1820](https://cplusplus.github.io/CWG/issues/1820.html) Qualified typedef names
- [x] (No) [CWG386](https://cplusplus.github.io/CWG/issues/386.html) Friend declaration of name brought in by _using-declaration_
- [ ] [CWG1839](https://cplusplus.github.io/CWG/issues/1839.html) Lookup of block-scope _extern_ declarations
- [x] (Clang 3.4) [CWG1818](https://cplusplus.github.io/CWG/issues/1818.html) Visibility and inherited language linkage
- [ ] [CWG2058](https://cplusplus.github.io/CWG/issues/2058.html) More errors from internal-linkage namespaces
- [x] (Clang 2.7) [CWG1900](https://cplusplus.github.io/CWG/issues/1900.html) Do `friend` declarations count as “previous declarations”?
- [x] (Clang 2.7) [CWG1477](https://cplusplus.github.io/CWG/issues/1477.html) Definition of a `friend` outside its namespace
- [x] (Partial) [CWG138](https://cplusplus.github.io/CWG/issues/138.html) Friend declaration name lookup
- [x] (Clang 3.3) [CWG563](https://cplusplus.github.io/CWG/issues/563.html) Linkage specification for objects
- [x] (Clang 2.8) [CWG110](https://cplusplus.github.io/CWG/issues/110.html) Can template functions and classes be declared in the same scope?
- [x] (Clang 2.7) [CWG1898](https://cplusplus.github.io/CWG/issues/1898.html) Use of “equivalent” in overload resolution
- [x] (Partial) [CWG1884](https://cplusplus.github.io/CWG/issues/1884.html) Unclear requirements for same-named external-linkage entities
- [x] (No) [CWG279](https://cplusplus.github.io/CWG/issues/279.html) Correspondence of "names for linkage purposes"
- [x] (Partial) [CWG338](https://cplusplus.github.io/CWG/issues/338.html) Enumerator name with linkage used as class name in other translation unit
- [ ] [CWG1252](https://cplusplus.github.io/CWG/issues/1252.html) Overloading member function templates based on dependent return type
- [ ] [CWG2062](https://cplusplus.github.io/CWG/issues/2062.html) Class template redeclaration requirements
- [ ] [CWG1896](https://cplusplus.github.io/CWG/issues/1896.html) Repeated alias templates
- [ ] [CWG1729](https://cplusplus.github.io/CWG/issues/1729.html) Matching declarations and definitions of variable templates

### Modules
No defect reports in this section.

### Parsing
- [ ] [CWG1828](https://cplusplus.github.io/CWG/issues/1828.html) _nested-name-specifier_ ambiguity
- [ ] [CWG1771](https://cplusplus.github.io/CWG/issues/1771.html) Restricted lookup in _nested-name-specifier_
- [ ] [CWG1835](https://cplusplus.github.io/CWG/issues/1835.html) Dependent member lookup before `<`
- [ ] [CWG1908](https://cplusplus.github.io/CWG/issues/1908.html) Dual destructor lookup and _template-id_s
- [ ] [CWG1841](https://cplusplus.github.io/CWG/issues/1841.html) `<` following template injected-class-name
- [ ] [CWG1616](https://cplusplus.github.io/CWG/issues/1616.html) Disambiguation parsing and template parameters

### Templates
- [ ] [CWG1936](https://cplusplus.github.io/CWG/issues/1936.html) Dependent _qualified-id_s
- [ ] [CWG1500](https://cplusplus.github.io/CWG/issues/1500.html) Name lookup of dependent conversion function
- [x] (Clang 23) [CWG2413](https://cplusplus.github.io/CWG/issues/2413.html) `typename` in _conversion-function-id_s
- [ ] [CWG1028](https://cplusplus.github.io/CWG/issues/1028.html) Dependent names in non-defining declarations
- [ ] [CWG1907](https://cplusplus.github.io/CWG/issues/1907.html) _using-declaration_s and default arguments
- [ ] [CWG2065](https://cplusplus.github.io/CWG/issues/2065.html) Current instantiation of a partial specialization
- [ ] [CWG1829](https://cplusplus.github.io/CWG/issues/1829.html) Dependent unnamed types
- [ ] [CWG1478](https://cplusplus.github.io/CWG/issues/1478.html) `template` keyword for dependent template template arguments
- [ ] [CWG2070](https://cplusplus.github.io/CWG/issues/2070.html) `using-declaration` with dependent `nested-name-specifier`
- [ ] [CWG852](https://cplusplus.github.io/CWG/issues/852.html) `using-declaration`s and dependent base classes
- [x] (Yes) [CWG2213](https://cplusplus.github.io/CWG/issues/2213.html) Forward declaration of partial specializations
- [ ] [CWG271](https://cplusplus.github.io/CWG/issues/271.html) Explicit instantiation and template argument deduction

**Comment by Endilll** [comment]
While there are some more currently under review, I put this paper on hold, until I have more time and a wording expert willing to spend their time to dive into this. As if definitions and lookup completeness sections weren't complicated enough, it gets even worse in subsequent sections.

**Comment by Endilll** [comment]
I got back to this recently with https://github.com/llvm/llvm-project/pull/106117 and https://github.com/llvm/llvm-project/pull/107019

**Comment by Endilll** [comment]
#113439 took care of CWG1898

**Comment by Endilll** [comment]
#113736 took care of 1884, 279, and 338.
