### ISSUE TITLE
[SPIR-V] Tracker for missing builtins in the SPIR-V backend

### ISSUE THREAD

**Issue by michalpaszkowski** [llvm/llvm-project#58070]
This issue and the following lists serves as a tracker for missing OpenCL/SPIR-V/... builtins discovered while testing the SPIR-V backend. The builtins will be incrementally implemented or fixed.

OpenCL:
- [ ] atomic_init()
- [ ] atomic_flag_test_and_set
- [ ] atomic_work_item_fence
- [ ] mem_fence(unsigned int)
- [ ] get_fence(void AS4*)
- [ ] wait_group_events(int, ocl_event AS4*)
- [ ] get_default_queue()
- [ ] get_image_num_mip_levels
- [ ] get_image_channel_data_type

SPIR-V:
- [ ] __spirv_Store(int*, int, int, int)
- [ ] __to_global
- [ ] __spirv_CreatePipeFromPipeStorage_write(__spirv_PipeStorage const AS1*)
- [ ] __get_kernel_work_group_size_impl

**Comment by michalpaszkowski** [comment]
Patch implementing `atomic_flag_test_and_set`, `atomic_flag_test_and_set_explicit`, `atomic_flag_clear`, `atomic_flag_clear_explicit`:

- [[SPIR-V] Add atomic_flag builtin implementation](https://reviews.llvm.org/D136310)

**Comment by iliya-diyachkov** [comment]
I'm still working on OpenCL's `enqueue_kernel` builtin function (it turns into the following calls in LLVM IR: `__enqueue_kernel_basic, __enqueue_kernel_basic_events, __enqueue_kernel_events_varargs, __enqueue_kernel_varargs`).

**Comment by iliya-diyachkov** [comment]
OpenCL's `enqueue_kernel` builtin function was supported:

- [[SPIRV] support enqueue_kernel builtin functions](https://reviews.llvm.org/D137018)

**Comment by iliya-diyachkov** [comment]
Two SPIR-V's builtin function (__spirv_Load/__spirv_Store) were supported:

- [[SPIRV] support __spirv_Load/Store builtin functions](https://reviews.llvm.org/D140490)
