### ISSUE TITLE
[MLIR] TODOs in NVGPU and NVVM Dialects

### ISSUE THREAD

**Issue by grypp** [llvm/llvm-project#69448]
I am working on NVGPU and NVVM dialects for Nvidia Hopper support. After having discussions at the LLVM US meeting, I want to make a list of improvements and opportunities in these dialects. I am looking for feedbacks and collaborations to refine and expand upon the following improvement goals in these dialects.

**TODOs in NVVM**
- [ ] PTX and SM Versions on the NVVM Ops
- [ ] NVVM Ops for Missing PTX Instructions
- [ ] Using BasicPtxBuilderInterface vs LLVM intrinsic

**TODOs in NVGPU**
- [ ] High-Level Ops for NVGPU Dialect
- [ ] Dynamic Shared Memory Support
- [ ] \(Optional) Splitting Host and Device Transformations in NVGPU/GPU dialect 

Below I have explained the individual tasks in detail.

**[NVVM] PTX and SM Versions on the NVVM Ops**

NVVM Ops don't include PTX or SM versions unlike LLVM intrinsics. This information is valuable for giving compilation errors, correct codegen, and etc.. We can encode PTX and SM versions on the Ops or somewhere in MLIR.  Currently, MLIR generates any intrinsic and let LLVM's ISEL complains that instruction isn't available for that target. Not nice :)

[LLVM intrinsic with SM and PTX info](https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/BuiltinsNVPTX.def#L655) vs [Same MLIR Op missing SM and PTX info ](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/LLVMIR/NVVMOps.td#L215-L227)

**[NVVM] NVVM Ops for Missing PTX Instructions**

The graph below illustrates the recent advancements in the PTX ISA. It's worth noting that neither LLVM's NVPTX backend nor MLIR's NVVM dialect fully supports the entire PTX model. It would be highly advantageous to include all PTX models and their associated options as NVVM Ops. We have already implemented some of newer PTX instructions as NVVM Ops, particularly to leverage the use of Ampere and Hopper tensor cores. However, I still believe that some PTX instruction or their options remain absent.

The lack of NVVM dialect could lead to duplication among different compilers. For example, OpenAI's Triton generates PTXs using a custom approach, and upstream MLIR employs [BasicPtxBuilderInterface](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/LLVMIR/IR/BasicPtxBuilderInterface.cpp) for similar reasons. We can unify these efforts within the NVVM dialect.

![Evolution of PTX ISA](https://github.com/llvm/llvm-project/assets/3865321/af6238be-6eee-4aa1-8e0c-7f6b3f73771c)

**[NVVM] BasicPtxBuilderInterface vs LLVM intrinsic**

The [BasicPtxBuilderInterface](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/LLVMIR/IR/BasicPtxBuilderInterface.cpp) was implemented to automatically generate PTX instructions as inline assembly from the tablegen Op, without typing C++. This interface also supports for PTX predication that LLVM's NVPTX backend does not (did not). It has become crucial in today's context for using Hopper's TMA (`cp.async.bulk`), Tensor Core instructions (`wgmma.mma_async`), arrive/wait barriers (`mbarrier`), and etc.

What's the best method for generating PTX instructions? Should we opt for this interface, or should we utilize LLVM intrinsics? In my opinion, the latter is the more suitable choice.

This interface is still remains important for generating PTX code quickly, especially for the evolving PTX ISA. 

(An example of an NVVM Op that utilizes this interface is (cp.async.bulk)](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/LLVMIR/NVVMOps.td#L1374-L1408)

### TODOs in NVGPU Dialect

**[NVGPU] High-Level Ops for NVGPU Dialect**

The NVVM dialect is intentionally designed to directly correspond to PTX instructions. Generating PTX requires specialized skills and can be highly complex, particularly when dealing with tensor cores. While the complexity serves a purpose, it is challenging for high-level compiler people to deal with descriptors, fragmented result registers, asynchrony, and more. It demands expertise.

On the other hand, we have the NVGPU dialect, which started incorporating high-level abstractions. Can we leverage the NVGPU dialect to simplify the use of NVVM?

For instance, let's look at the `nvgpu.wargroup.mma` below. It performs a warp-group level GEMM for `128x128x64` shape with `f32 += f16 * f16` data types. Many can understand this Op and generate and start using. In contrast, the actual PTX code is notably complex. It involves aspects such as asynchrony, iteration over the 64-bit wgmma descriptors, matrix-b transposition, and the selection of 'n' (with 'm' and 'k' being constants as per PTX specifications), grouping multiple `wgmma.mma_async` instructions to complete the given shape. 

```
%matrixD = nvgpu.wargroup.mma %wgmmaDescA, %wgmmaDescB, %matrixC {transposeB}:
!nvgpu.wgmma.descriptor<tensor = memref<128x64xf16, 3>>,
!nvgpu.wgmma.descriptor<tensor = memref<64x128xf16, 3>>,
!nvgpu.wargroup.accumulator<fragmented = vector<128x128xf32>>
->
!nvgpu.wargroup.accumulator<fragmented = vector<128x128xf32>>
```

The PTX instructions generated from this Op are as follows. If you are not familiar with PTX, piecing together the following PTX code can be quite challenging.

```
wgmma.fence.sync.aligned;
wgmma.mma_async.sync.aligned.m64n128k16.f32.f16.f16 {%f1, %f2,...}, %dA, %dB, p, 1, 1, 0, 1;
wgmma.mma_async.sync.aligned.m64n128k16.f32.f16.f16 {%f1, %f2,...}, %dA+2, %dB+128, p, 1, 1, 0, 1;
wgmma.mma_async.sync.aligned.m64n128k16.f32.f16.f16 {%f1, %f2,...}, %dA+4, %dB+256, p, 1, 1, 0, 1;
wgmma.mma_async.sync.aligned.m64n128k16.f32.f16.f16 {%f1, %f2,...}, %dA+8, %dB+348, p, 1, 1, 0, 1;
wgmma.mma_async.sync.aligned.m64n128k16.f32.f16.f16 {%f500,%f501,...} %dA+512, %dB, p, 1, 1, 0, 1;
wgmma.mma_async.sync.aligned.m64n128k16.f32.f16.f16 {%f500,%f501,...} %dA+514, %dB+128, p, 1, 1, 0, 1;
wgmma.mma_async.sync.aligned.m64n128k16.f32.f16.f16 {%f500,%f501,...} %dA+516, %dB+256, p, 1, 1, 0, 1;
wgmma.mma_async.sync.aligned.m64n128k16.f32.f16.f16 {%f500,%f501,...} %dA+518, %dB+348, p, 1, 1, 0, 1;
wgmma.commit_group.sync.aligned;
wgmma.wait_group.sync.aligned 1;
```

**[NVGPU] Dynamic Shared Memory Support**

Currently, there isn't a practical method for using dynamic shared memory, whether in the NVGPU or GPU dialects. One workaround is to create 0-sized global memrefs or LLVM arrays, but this approach seems somewhat ugly (works because it fits LLVM's NVPTX expectations). I believe we can handle this more elegantly in MLIR, and hide the uggliness behind this dialects.

[Example of using 0-sized memref](https://github.com/llvm/llvm-project/blob/main/mlir/test/Conversion/NVGPUToNVVM/nvgpu-to-nvvm.mlir#L665)

**[NVGPU/GPU] Splitting Host and Device Transformations**

In the NVGPU and GPU dialects, some Ops are for host and some for device. Host Ops are usually lowered into runtime calls, while device Ops are lowered into PTX or intrinsics. They are conceptually different, and it may be worthwhile to consider splitting the transformation pass.

If you are constructing your pass pipeline in MLIR, having separate host and device passes would be more clear in my opinion (but no strong opinion here)

**Comment by joker-eph** [comment]
By the way, what about all the things that Triton put together to work around missing pieces upstream? 
It'd be nice to make sure this all get upstream right? (There is another PTXBuilder there, and they are bypassing NVVM because of a few missing things, I head about load/store that can have cache policy and evict policy).
@ThomasRaoux : do you have inputs?

**Comment by ThomasRaoux** [comment]
> By the way, what about all the things that Triton put together to work around missing pieces upstream? It'd be nice to make sure this all get upstream right? (There is another PTXBuilder there, and they are bypassing NVVM because of a few missing things, I head about load/store that can have cache policy and evict policy). @ThomasRaoux : do you have inputs?

Triton uses its PTX builder to generate inline asm in few cases including controlling the rounding mode for type conversions, supporting loads with predicates and all the variants of cache policy and other and finally for mma operations.

I'm not sure triton will find enough incentives to move to nvvm even if those were available there, for one thing it tends to be simpler and give more flexibly to generate the inline ptx directly rather than having to deal with an op signature which may not be exactly what is needed. On the other end having an extra nvvm op which is short lived and will lower to inline ptx doesn't bring a lot. It does make the IR nicer at the nvvm level but since this is not a good level to optimize it doesn't bring a lot of benefits.

Having llvm intrinsics can help in some cases as it allows representing side effect with more details. For instance we recently moved to using the nvvm.shuffle intrinsics to be able to use the `convergent` attribute.

I don't have much opinions on nvgpu part as this is something triton cannot use. I assume the design decision highly depend on what end to end software stack would use it.

**Comment by joker-eph** [comment]
> I'm not sure triton will find enough incentives to move to nvvm even if those were available there, for one thing it tends to be simpler and give more flexibly to generate the inline ptx directly rather than having to deal with an op signature which may not be exactly what is needed.

Interesting (and surprising to me): I would have thought that on the opposite having a clean API to express "I want this sequence" instead of repeated use of the PTX build to reconstruct the same sequence in various places would be preferred (+ type safety, + verification ...).

> On the other end having an extra nvvm op which is short lived and will lower to inline ptx doesn't bring a lot.

This is temporary though: LLVM should evolve to support all the intrinsics matching the NVVM dialect ultimately. If only for compile-time: some recent internal measurement showed that inline ASM for some case was bloating the LLVM IR (because of repeated packing/unpacking struct surrounding these) and the source of compile-time issues we see.

> I don't have much opinions on nvgpu part as this is something triton cannot use.

There is a NVGPU inside Triton as well, mind commenting on this one?

**Comment by ThomasRaoux** [comment]
> > I'm not sure triton will find enough incentives to move to nvvm even if those were available there, for one thing it tends to be simpler and give more flexibly to generate the inline ptx directly rather than having to deal with an op signature which may not be exactly what is needed.
> 
> Interesting (and surprising to me): I would have thought that on the opposite having a clean API to express "I want this sequence" instead of repeated use of the PTX build to reconstruct the same sequence in various places would be preferred (+ type safety, + verification ...).
> 

In general the repeated use of PTX build can be handled by layering the code well. What I'm trying to say is that the gain is small as building the ptx is not a lot of code and trying to move it upstream increases the surface area between triton and MLIR so the ROI is not clear.

> Also you haven't commented on the PTXBuilder divergence/redundancy?
> 

This is the same problem, the upstream PTXBuilder does look nice and maybe triton should move to it at some point but this is a small amount of code so the ROI is not big.

> > On the other end having an extra nvvm op which is short lived and will lower to inline ptx doesn't bring a lot.
> 
> This is temporary though: LLVM should evolve to support all the intrinsics matching the NVVM dialect ultimately. If only for compile-time: some recent internal measurement showed that inline ASM for some case was bloating the LLVM IR (because of repeated packing/unpacking struct surrounding these) and the source of compile-time issues we see.
> 

Interesting, why does the inline asm have a different signature than the equivalent intrinsic? Having more intrinsics would be nice for some parts but I don't think it can replace everything, for instance the predicated load would probably not be exposed as intrinsic.

> > I don't have much opinions on nvgpu part as this is something triton cannot use.
> 
> There is a NVGPU inside Triton as well, mind commenting on this one?

NVGPU in triton is actually very similar to some of the nvvm ops added by Guray and very different than upstream nvgpu. It is just there to abstract some operations that get then converted to inline asm. That's probably where there is re-use opportunity with the nvvm work actually. Most likely this dialect would go away if the equivalent intrinsics were added to llvm.

**Comment by joker-eph** [comment]
> In general the repeated use of PTX build can be handled by layering the code well. What I'm trying to say is that the gain is small as building the ptx is not a lot of code and trying to move it upstream increases the surface area between triton and MLIR so the ROI is not clear.

Let me clarify a bit my goal here: I'm looking at "how to make MLIR NVVM better?", and Triton is a great end-to-end case-study so I'm "using you" to drive the list of improvements upstream. Whether Triton would actually adopt anything or not is almost rhetorical here! ;) 
(the aim is for all the potential future compilers using MLIR out-there having an easier way to target Nvidia GPUs!)

> This is the same problem, the upstream PTXBuilder does look nice and maybe triton should move to it at some point but this is a small amount of code so the ROI is not big.

I was asking because I thought you'd have a list of missing features (or reason why the current API is inconvenient) in the upstream PTXBuilder :)

**Comment by grypp** [comment]
We had a great chat with @ThomasRaoux during the llvm meeting, thanks for clarifying your thoughts here. Thanks Mehdi for involving him. I'm enthusiastic about shaping the NVVM/NVGPU dialect to better suit everyone needs. 

> > There is a NVGPU inside Triton as well, mind commenting on this one?
>
> NVGPU in triton is actually very similar to some of the nvvm ops added by Guray and very different than upstream nvgpu. It is just there to abstract some operations that get then converted to inline asm. 

I agree with your assessment. Triton has one more dialect as far as I can see. The mapping appears to be as follows (correct me if it is wrong):
- Triton `triton_nvidia_gpu` -> Upstream `NVGPU`
- Triton `NVGPU` -> Upstream `NVVM` (almost 1to1 to PTX)


> That's probably where there is re-use opportunity with the nvvm work actually. Most likely this dialect would go away if the equivalent intrinsics were added to llvm.

Agreed. Re-using upstream's `NVVM` dialect can be the first step unifying these efforts. It reduces code duplication and strengthens the `NVVM` dialect. Using NVVM also gives for a smooth transition when LLVM core gains intrinsics. I've listed the necessary improvements for the `NVVM` dialect in this task, and we can both benefit of them :)

To illustrate the similarities between the dialects, I compared a complex operation, the warp-group matrix-matrix multiplication (warp-group mma), in both dialects. They are remarkably similar, using almost same types, generates the same PTX.

Triton NVGPU Dialect:
```
%res = nvgpu.wgmma %descA, %descB, %matrixAcc {m=64:i32, n=128:i32, k=16:i32, eltTypeC=7:i32, eltTypeA=4:i32, eltTypeB=4:i32, layoutA=0:i32, layoutB=0:i32} : (i64, i64, !llvm.struct<(f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32)>) -> (!llvm.struct<(f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32)>)
```
Upstream MLIR NVVM Dialect:
```
%res = nvvm.wgmma.mma_async %descA, %descB, <m = 64, n = 128, k = 16>, D[%matrixAcc, <one>, <wrapped>], A[<f16>, <one>, <row>], B[<f16>, <one>, <col>] : !llvm.struct<(f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32)> -> !llvm.struct<(f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32)>
```




> Let me clarify a bit my goal here: I'm looking at "how to make MLIR NVVM better?", and Triton is a great end-to-end case-study so I'm "using you" to drive the list of improvements upstream. Whether Triton would actually adopt anything or not is almost rhetorical here! ;)
(the aim is for all the potential future compilers using MLIR out-there having an easier way to target Nvidia GPUs!)

What about also "how to make MLIR NVGPU better?"? Generating the `NVVM` is massively hard unless you're NVIDIA ninja. The `NVGPU` dialect plays a crucial role in bridging the gap between high-level dialects.

For instance, `linalg` would not directly lower to `NVVM`, that's big abstraction jump. Triton doesn't do neither, targets `triton_nvidia_gpu` from Triton GPU dialect. Wouldn't it be great we all use Upstream's `NVGPU` instead? 

Though reusing is a challenge due to Triton using different types, but the OPs are similar (can be even more). So there is hope :)

Let's take complex warp-group mma OPs below, where both dialects generate [numerous lines of PTX/NVVM code](https://github.com/llvm/llvm-project/blob/main/mlir/test/Conversion/NVGPUToNVVM/nvgpu-to-nvvm.mlir#L798-L839).

Triton triton_nvidia_gpu Dialect:
```
%matrixD = triton_nvidia_gpu.dot_async %matrixA, %matrixB, %matrixC: 
            tensor<128x64xf16, #shared1> * tensor<64x128xf16, #shared2> 
            -> tensor<128x128xf32, #mma>
```

Upstream MLIR NVGPU Dialect:
```
%matrixD = nvgpu.warpgroup.mma %matrixA, %matrixB, %matrixC {transposeB}: 
      !nvgpu.warpgroup.descriptor<tensor = memref<128x64xf16, 3>>, 
      !nvgpu.warpgroup.descriptor<tensor = memref<64x128xf16, 3>>, 
      !nvgpu.warpgroup.accumulator<fragmented = vector<128x128xf32>> 
      -> 
      !nvgpu.warpgroup.accumulator<fragmented = vector<128x128xf32>>  
```

The both Codegen takes following steps:

1) Selecting the appropriate wgmma.mma_async instruction size.
2) Generating multiple wgmma.mma_async group to complete the given shape.
3) Ensuring the registers are correctly positioned.
4) Iterating wgmma descriptors accurately.
5) Waiting to wait for the wgmma group to complete.

The primary difference is the types. Perhaps we can make these types more generic and consolidate them within the NVGPU dialect to simplify the process.

**Comment by joker-eph** [comment]
> What about also "how to make MLIR NVGPU better?"? 

Sure :) 
NVVM and NVGPU seems pretty important to make better! Thanks a lot for working on this. Triton isn't the last GPU compiler written, and we're lowering the barrier to entry to write more compilers using NVVM.
