### ISSUE TITLE
[HLSL] Track HLSL "standard library" Implementation

### ISSUE THREAD

**Issue by damyanp** [llvm/llvm-project#89663]
HLSL has many intrinsics, functions and data types that will need to be implemented.  

We need a centralized list of all these things, which shader model and stages they apply to, and the state of the implementation of each one.

The list needs to be publicly available, linked to issues in github, and able to automatically updated based on the states of the issues. 

> *Open Question* - should we expand this to cover tracking DXIL op implementations? Maybe for each thing we track here we cover from HLSL lowered down to final IR?

# Acceptance Criteria

- [x] Anyone can easily find the current progress of intrinsic implementations
- [x] Systems are in place so we can be confident that the information is up to date (or is at least updateable)
- [ ] Issues have been created for at least all intrinsics we plan implement over the next 6 months

# Subtasks

- [ ] Design method for tracking and reporting this
- [x] Collect data for intrinsics
- [x] Collect data for built in types & APIs
- [ ] anything else??

**Comment by farzonl** [comment]
reporting\issue creation: https://github.com/farzonl/test_repo/issues
If this looks good we should start testing on llvm-project

tracking progress:  https://github.com/farzonl/HLSLDocGenerator/blob/master/git_llvm_jupyter.ipynb

collect data on intrinsics: https://github.com/farzonl/HLSLDocGenerator/blob/master/query_jupyter.ipynb
