### ISSUE TITLE
[HLSL] Add Intangible AST Type

### ISSUE THREAD

**Issue by llvm-beanz** [llvm/llvm-project#90631]
HLSL has a set of _intangible types_, which are described in in the [draft HLSL Specification (**[Basic.types]**)](https://microsoft.github.io/hlsl-specs/specs/hlsl.pdf):
> There are special implementation-defined types such as handle types, which fall into a category of standard intangible types. Intangible types are types that have no defined object representation or value representation, as such the size is unknown at compile time.
>
> A class type T is an intangible class type if it contains an base classes or members of intangible class type, standard intangible type, or arrays of such types. Standard intangible types and intangible class types are collectively called intangible types([9](https://microsoft.github.io/hlsl-specs/specs/hlsl.html#Intangible)).

We need to add a new AST type for intangible types, and a way to generate the appropriate handle types.

## Acceptance Criteria
- [x] llvm/llvm-project#97362
- [ ] llvm/llvm-project#102954
- [ ] llvm/llvm-project#84824

**Comment by bogner** [comment]
Superceded by #101557
