### ISSUE TITLE
[HLSL] Split up the HLSLResource attribute

### ISSUE THREAD

**Issue by bogner** [llvm/llvm-project#98192]
The [HLSLResource attribute](https://github.com/llvm/llvm-project/blob/release/18.x/clang/include/clang/Basic/Attr.td#L4336) is currently used to represent resource related information in the AST for lowering and diagnostic purposes. It is unspellable and it's attached to resource types like RWBuffer and RasterizerOrderedBuffer when they're created in HLSLExternalSemaSource.

As we move towards using intangible types for handles (See llvm/llvm-project#90631, llvm/llvm-project#97362), we want to work towards a model where this attribute is no longer monolithic and applies to the type of the handle itself. A few possibly incomplete examples:
```c++
template <typename T> class RWBuffer {
  __hlsl_resource_t [[hlsl::contained_type(T), hlsl::is_rov(false),
                      hlsl::resource_class(uav)]] Handle;
};

template <typename T> class ConstantBuffer {
  __hlsl_resource_t [[hlsl::resource_class(cbuffer)]] Handle;
}

template <typename T> class Texture2D {
  __hlsl_resource_t
      [[hlsl::texture_dimension(...), hlsl::resource_class(srv)]] Handle;
}
```

To get there, we need to do a few things:
- [x] llvm/llvm-project#98193
- [x] llvm/llvm-project#98556
- [x] llvm/llvm-project#102392
- [ ] llvm/wg-hlsl#39
- [ ] Remove HLSLResource
- [ ] Figure out diagnostic story for attributes when spelled

**Comment by bogner** [comment]
The remaining work here is tracked in #101557
